# Info
site_name: Qlog
site_url: https://lixiaoqi-LXQ.github.io
site_description: The name `Qlog` is inspired by Dlog.

# theme: material
theme:
  name: material
  logo: img/touxiang.png
  favicon: img/favicon.ico
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    # hence the back-to-top is there, there's no need for sticky tabs!
    # Improvement for vision and sacrifice on user experience
    # - navigation.tabs.sticky
    - navigation.top
    - toc.follow

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: 切换至夜间模式
      primary: white
      accent: cyan

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: 切换至日间模式
      primary: white
      accent: indigo

# Left bottom
copyright: Copyright &copy; 2022 李晓奇 # 左下角的版权声明


nav:
  - Qlog: index.md
  - 随机思考:
    - 9.19: jottings/220919.md
  - HW:
    - NETWORK:
      - HW1: HW/HW1.md
      - HW2: HW/HW2.md

markdown_extensions:
  - admonition # `!!! note` syntax
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_javascript:
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
  - mkdocs/css/unordered-list-symbols.css

